### ISSUE TITLE
setup / install

### ISSUE THREAD

**Issue by dcsan** [David-Desmaisons/Vue.D3.sunburst#1]
the component looks great, but I'm having a bit of trouble getting started. Not specific to your sunburst code, but just how to use this external component in a vue project, hope you don't mind me asking here.

I have added the component to package.json in client side of my app.
but i get this `module not found` error

```
ERROR in ./src/pages/TreePage.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/TreePage.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'vue-d3-sunburst' in '/Users/dc/dev/rikai/nap/web-app/client/src/pages'
 @ ./src/pages/TreePage.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/TreePage.vue?vue&type=script&lang=js&) 53:0-110 57:21-36 58:22-38 59:23-40 60:14-22 61:17-28
```

I'm using a build script and babel to transofrm

Is there some other webpack or other configuration that I need to setup?

**Comment by David-Desmaisons** [comment]
Did you run npm i vue-d3-sunburst --s ?

**Comment by dcsan** [comment]
yes indeed, and it's available in my `node_modules` client side. also in the `package.json`

**Comment by David-Desmaisons** [comment]
Could you share TreePage.vue code?

**Comment by David-Desmaisons** [comment]
@dcsan , I updated the package.json with correct main files. Everything should work fine now.

**Comment by dcsan** [comment]
thanks! I moved on to another approach but would like to use this for something else another time.
