### ISSUE TITLE
color-scheme option broken

### ISSUE THREAD

**Issue by ErikBjare** [David-Desmaisons/Vue.D3.sunburst#11]
First off: Thanks for making this, using it has been a really smooth experience!

Setting any color scheme other than the default seems to mess up the coloring.

I first noticed it in the demo, works fine until you switch to any other scheme. Here's a screenshot:

![image](https://user-images.githubusercontent.com/1405370/67129063-e73c0100-f1fd-11e9-8f63-935c1a7f601c.png)

I replicated it in the thing I'm building as well, would be nice to have it working (I might hunt it down myself, but don't hold your breath).

**Comment by David-Desmaisons** [comment]
I just reprodruced...Should be a recent regression, I will investigate.

**Comment by David-Desmaisons** [comment]
Corrected in version 1.0.1
