### ISSUE TITLE
Labeling arcs

### ISSUE THREAD

**Issue by ErikBjare** [David-Desmaisons/Vue.D3.sunburst#14]
I'm building [ActivityWatch](https://github.com/ActivityWatch/activitywatch) and we're using this lib for our sunburst visualization of time spent per category. ([again](https://github.com/David-Desmaisons/Vue.D3.sunburst/issues/11#issue-509316033), thanks!)

We've implemented the hover feature to show information about the represented data, but it's hard to get an overview at a glance, which makes me want to implement labeling of the arcs similar to what I've had in some of my Python visualizations:

![image](https://user-images.githubusercontent.com/1405370/97691686-f60af400-1a9e-11eb-996a-e479b3d41cc1.png)

I'm not super skilled at D3, but I'm just posting it here in case it piques someone's attention/interest, and to keep myself accountable in case I drop the ball.

Something akin to this: http://bl.ocks.org/metmajer/5480307

I found this for creating rounded text (might not be the best way to go, but still): https://www.visualcinnamon.com/2015/09/placing-text-on-arcs.html

**Comment by David-Desmaisons** [comment]
Hello Erik,
Finally I am working on this.
I somehow ended-up not remenbering your original PR and writing another PR for this topic. Rigth now I am comparing the two PRs and incorporating some of the layout improvements you implemented. The good thing is that my implementation correct some bugs that hapened when playing with labels and minimal arc at the same time.
Hopefully we will have a "best of both word" implementation soon. I expect to merge the PR ans create a new version of the lib this week.
Thanks for contributing,
David
________________________________
De : Erik Bjäreholt ***@***.***>
Envoyé : vendredi 30 octobre 2020 07:01
À : David-Desmaisons/Vue.D3.sunburst ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [David-Desmaisons/Vue.D3.sunburst] Labeling arcs (#14)


I'm building ActivityWatch<https://github.com/ActivityWatch/activitywatch> and we're using this lib for our sunburst visualization of time spent per category. (again<https://github.com/David-Desmaisons/Vue.D3.sunburst/issues/11#issue-509316033>, thanks!)

We've implemented the hover feature to show information about the represented data, but it's hard to get an overview at a glance, which makes me want to implement labeling of the arcs similar to what I've had in some of my Python visualizations:

[image]<https://user-images.githubusercontent.com/1405370/97691686-f60af400-1a9e-11eb-996a-e479b3d41cc1.png>

I found this for creating rounded text (might not be the best way to go, but still): https://www.visualcinnamon.com/2015/09/placing-text-on-arcs.html

I'm not super skilled at D3, but I'm just posting it here in case it piques someone's attention/interest, and to keep myself accountable in case I drop the ball.

**Comment by ErikBjare** [comment]
Awesome! Thanks for getting this done! :)
