### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by localgod** [David-Desmaisons/Vue.D3.sunburst#2]
As might be seen in the attached image I'm experiencing some scaling issues with your component.
 
<img width="583" alt="screen shot 2018-09-23 at 17 10 12" src="https://user-images.githubusercontent.com/1308965/45929543-9d79dc00-bf53-11e8-845e-911b6d044ff1.png">

<img width="597" alt="screen shot 2018-09-23 at 17 15 30" src="https://user-images.githubusercontent.com/1308965/45929608-53ddc100-bf54-11e8-81ca-2652a480d062.png">

I have tried to fix the issue with various css rules, but this has no effect on the size of the diagram only the element containing it. 

How to I modify the width of the individual elements of the breadcrum and how do I scale up the diagram?

**Comment by David-Desmaisons** [comment]
1) Import component css:
```javascript
import "vue-d3-sunburst/dist/vue-d3-sunburst.css";

This would probably resolve the main part of your problem,

2) Take a look at [breadcrumbtail props](https://github.com/David-Desmaisons/Vue.D3.sunburst#props-1). Layout can be customized with width/height/... props.

3) The breadcrumbtail component provided by this lib is just a component that can be used as a `legend` slot for the main component. You can provide your own implementation to better fit your needs.

**Comment by localgod** [comment]
So imported the css and it fixed most of my problems:
![screen shot 2018-09-24 at 18 36 09](https://user-images.githubusercontent.com/1308965/45965446-c5873f00-c028-11e8-82fb-cc8cfaf6c3b8.png)

I tried different options with the breadcrumb but can't really make it work with my long names. This is my config:

```
<breadcrumbTrail
  id="breadcrumbs"
  :width="width"
  slot="top"
  slot-scope="{ nodes,colorGetter,width}"
  :current="nodes.mouseOver"
  :root="nodes.root"
  :colorGetter="colorGetter"
  :from="nodes.clicked" />
```

Any hints on where I might have gone wrong?

If I set `item-width` like this:

```
<breadcrumbTrail
  id="breadcrumbs"
  item-width="200"
  :width="width"
  slot="top"
  slot-scope="{ nodes,colorGetter,width}"
  :current="nodes.mouseOver"
  :root="nodes.root"
  :colorGetter="colorGetter"
  :from="nodes.clicked" />
```

I get this:

![screen shot 2018-09-24 at 18 41 58](https://user-images.githubusercontent.com/1308965/45965740-99b88900-c029-11e8-9f17-524a60c89a5c.png)

which makes little sense.

**Comment by David-Desmaisons** [comment]
@localgod  Any new on this?

**Comment by David-Desmaisons** [comment]
Please re-open, if you did not solve it and can share more info.
