### ISSUE TITLE
Minimal arc angle to be displayed when Zoomed in

### ISSUE THREAD

**Issue by isaacbernat** [David-Desmaisons/Vue.D3.sunburst#5]
Every time a section is zoomed in, all their children increase in area. Therefore, their angles also become bigger. Nevertheless, the "Minimal arc angle" information doesn't seem to be recomputed, as subsequent children, which became bigger than it, should be displayed and are not.

**Comment by David-Desmaisons** [comment]
Hello @isaacbernat , thanks for reporting this. This is a limitation, I was aware of.
I will work on a fix in the short term.

**Comment by David-Desmaisons** [comment]
Any feebacks on my comments?

**Comment by isaacbernat** [comment]
Your comments are that you are aware of the limitation and you will fix it, right? My feedback is 👍

**Comment by David-Desmaisons** [comment]
@isaacbernat, I just realize that my last comment was referring to another issue. I will take a closer look at potential fix for this one at a latter time.

**Comment by David-Desmaisons** [comment]
Corrected in version 1.8.1
