### ISSUE TITLE
Colour schemes and colour blocking children

### ISSUE THREAD

**Issue by sophiabarclay** [David-Desmaisons/Vue.D3.sunburst#8]
Is there a way to pass down the same colour from parent data to children data so that children data is organised into colour blocks that relate directly to their parent?

This is possible with the D3 Zoomable Sunburst, as seen in this example:

<img width="799" alt="Screenshot 2019-04-09 at 16 38 10" src="https://user-images.githubusercontent.com/43184890/55814357-3df5af00-5ae6-11e9-8264-d49b41f2408e.png">

Also, is it possible to create customised colour schemes? Thanks!

**Comment by David-Desmaisons** [comment]
1) Yes: check getCategoryForColor props
2) Check the demo for all the colour schemes, currently 8 D3 schemes are supported:
https://david-desmaisons.github.io/Vue.D3.sunburst/
