### ISSUE TITLE
How can i set the color of a single node without relying on d3 themes?

### ISSUE THREAD

**Issue by Brucuz** [David-Desmaisons/Vue.D3.sunburst#9]

**Comment by David-Desmaisons** [comment]
What is your scenario?

**Comment by matthieucov** [comment]
Hello David, I have a similar question. 
I would like to pass a color for a given node given the value of the size or another parameter. It seems that the `colorTheme` is only supporting d3 themes right now?

**Comment by ErikBjare** [comment]
This can now be done with `get-category-for-color`, so the issue can be closed.

**Comment by David-Desmaisons** [comment]
Use `get-category-for-color`
